name: 'Setup uv Environment'
description: 'Setup uv Environment'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
runs:
  using: "composite"
  steps:
    - id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - run: |
        python -m pip install -U pip
        python -m pip install -U uv uv-dynamic-versioning
        export UV_PROJECT_ENVIRONMENT="${{ steps.setup-python.outputs.pythonLocation }}"
        echo "UV_PROJECT_ENVIRONMENT is set to $UV_PROJECT_ENVIRONMENT"
        uv sync --frozen
      shell: bash