name: 'Setup uv Environment'
description: 'Setup uv Environment'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        uv sync --frozen
      shell: bash