name: 'Setup uv Environment'
description: 'Setup uv Environment'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - run: |
        python -m pip install -U pip
        python -m pip install -U uv uv-dynamic-versioning
        python_path=$(which python)
        python_root_dir=$(dirname $(dirname $python_path))
        export UV_PROJECT_ENVIRONMENT=$python_root_dir
        echo "UV_PROJECT_ENVIRONMENT is set to $UV_PROJECT_ENVIRONMENT"
        uv sync --frozen
      shell: bash