name: Test
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}
          registry-username: ${{ secrets.UV_INDEX_ROCHE_USERNAME }}
          registry-password: ${{ secrets.UV_INDEX_ROCHE_PASSWORD }}
      - name: 'Run Linting'
        run: |
          ruff format --check .
          ruff check .
      - name: 'Run Unit Tests'
        run: |
          pytest tests --junitxml=pytest-junit.xml --cov=src/remcs_ai --cov-report xml:pytest-coverage.xml
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: junit and cobertura
          path: |
            pytest-junit.xml
            pytest-coverage.xml
          retention-days: 7
      - name: Pytest coverage comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: MishaKav/pytest-coverage-comment@v1.1.51
        with:
          pytest-xml-coverage-path: ./pytest-coverage.xml
          junitxml-path: pytest-junit.xml
          hide-report: true